name: pytorch-CycleGAN-and-pix2pix
channels:
- peterjc123
- pytorch
- defaults
dependencies:
- python=3.5.5
- pytorch=0.4.1
- scipy
- pip:
  - torchvision==0.2.2.post3
  - dominate==2.3.1
  - Pillow==5.0.0
  - numpy==1.14.1
  - visdom==0.1.7
